export enum ExtraStatType {
  None,
  InvokerCurrentHP,
  TargetCurrentHP,
  InvokerMaxHP,
  TargetMaxHP,
  InvokerLostHP,
  TargetLostHP,
  InvokerMaxHPCapGaugeValue,
  TargetMaxHPCapGaugeValue,
}
export enum HeroStatus {
  None,
  Dead = 0x44c,
  Dying = 0x456,
  Exiled = 0x47e,
  Suppressed = 0x4b0,
  Stasis = 0x514,
  Knockback = 0x582,
  Pulling = 0x58c,
  Airborn = 0x596,
  Stoned = 0x5dc,
  Stunned = 0x640,
  Paralysis,
  Emp,
  Purify,
  Groggy,
  Hit,
  Frozen,
  Panic = 0x64a,
  Charmed = 0x6ae,
  Fear = 0x6b8,
  Polymorph = 0x708,
  ForcedIdle = 0x76c,
  Taunted = 0x834,
  ConcentratedTarget = 0x83e,
  Confusion = 0x848,
  MindControlled = 0x898,
  Silence = 0x8fc,
  Blind = 0x960,
  Entangle = 0x9c4,
  Slow,
  Immortal = 0xa8c,
  Indestructible,
  DisableNormalAttack = 0xa28,
  DisableExSkill,
  DisablePassiveSkill,
  DisablePublicSkill,
  ImmuneDamageAttack = 0xc4e,
  ImmuneDamageAll,
  ImmuneDamageBySkillType,
  ImmuneDead = 0xc8a,
  ImmuneStoned = 0xc94,
  ImmuneKnockback = 0xc9e,
  ImmunePulling = 0xca8,
  ImmuneAirborn = 0xcb2,
  ImmuneStunned = 0xcbc,
  ImmuneCharmed = 0xcc6,
  ImmuneFear = 0xcd0,
  ImmunePolymorph = 0xcda,
  ImmuneForcedIdle = 0xce4,
  ImmuneMindControl = 0xcee,
  ImmuneSilence = 0xcf8,
  ImmuneBlind = 0xd02,
  ImmuneParalysis = 0xd0c,
  ImmuneEmp = 0xd16,
  ImmunePurify = 0xd20,
  ImmuneGroggy = 0xd2a,
  ImmuneConcentratedTarget,
  ImmuneConfusion,
  ImmuneCrowdControl = 0xdb6,
  ImmuneGroggyGaugeAdd = 0xdc0,
  Rage = 0x1004,
  Untargetable = 0x1068,
  Metamorph = 0x1130,
  Thorns = 0x1388,
  All = 0x7fffffff,
}
export enum LogicEffectEndCondition {
  None,
  Duration,
  ReloadCount,
  AmmoCount,
  AmmoHit,
  UseExSkillCount,
}
export enum DamageCriticalType {
  None,
  Never,
  Check,
  Always,
}
