/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionButton: typeof import('./components/ActionButton.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BG: typeof import('./components/GameImg/BG.vue')['default']
    Collect: typeof import('./components/character/Collect.vue')['default']
    Currency: typeof import('./components/parcel/Currency.vue')['default']
    Equip: typeof import('./components/character/Equip.vue')['default']
    Equipment: typeof import('./components/parcel/Equipment.vue')['default']
    EventBonus: typeof import('./components/event/EventBonus.vue')['default']
    EventCurrency: typeof import('./components/event/EventCurrency.vue')['default']
    EventList: typeof import('./components/event/EventList.vue')['default']
    EventStage: typeof import('./components/event/EventStage.vue')['default']
    EventStageReward: typeof import('./components/event/EventStageReward.vue')['default']
    FiveOO: typeof import('./components/warn/FiveOO.vue')['default']
    FourOFour: typeof import('./components/warn/FourOFour.vue')['default']
    Furniture: typeof import('./components/parcel/Furniture.vue')['default']
    GachaGroup: typeof import('./components/parcel/GachaGroup.vue')['default']
    GachaGroupSub: typeof import('./components/parcel/GachaGroupSub.vue')['default']
    GameImg: typeof import('./components/GameImg/GameImg.vue')['default']
    Gear: typeof import('./components/character/Gear.vue')['default']
    GuideMission: typeof import('./components/guide/GuideMission.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Item: typeof import('./components/parcel/Item.vue')['default']
    NoError: typeof import('./components/warn/NoError.vue')['default']
    Parcel: typeof import('./components/parcel/Parcel.vue')['default']
    ParcelCommon: typeof import('./components/parcel/ParcelCommon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShopItem: typeof import('./components/shop/ShopItem.vue')['default']
    ShopPage: typeof import('./components/shop/ShopPage.vue')['default']
    Slider: typeof import('./components/character/Slider.vue')['default']
    SpineCharacter: typeof import('./components/character/SpineCharacter.vue')['default']
    TabBasic: typeof import('./components/character/TabBasic.vue')['default']
    WIP: typeof import('./components/warn/WIP.vue')['default']
  }
}
