/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Collect: typeof import('./components/character/Collect.vue')['default']
    GameImg: typeof import('./components/GameImg/GameImg.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Icon: typeof import('./components/parcel/Icon.vue')['default']
    Item: typeof import('./components/parcel/Item.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShopItem: typeof import('./components/shop/ShopItem.vue')['default']
    ShopPage: typeof import('./components/shop/ShopPage.vue')['default']
  }
}
